########################################################
#                                                      #
#  __   __   __               ___    __   ___          #
# /__` /  \ /  ` |  /\  |    |__  | |__) |__           #
# .__/ \__/ \__, | /~~\ |___ |    | |  \ |___          #
#                                                      #
#  __   __        ___         __       ___    __       #
# /  ` /  \ |\ | |__  | |  | |__)  /\   |  | /  \ |\ | #
# \__, \__/ | \| |    | \__/ |  \ /~~\  |  | \__/ | \| #
#                                                      #
########################################################

announcements:
  store:
    link: https://store.xyz.abc # Click link for chat message
    interval: 180 # Delay between each message in seconds
    sound: "ENTITY_PLAYER_LEVELUP" # Sound to play when message is sent
    message: |-
      &f
      &e🛒 Server Store

      &fPurchase &eranks, coins, keys &fand much
      &fmore at our &estore & support &fthe server!

      &e➟ &nstore.xyz.abc
      &f
    "action-bar": "§e🛒 &lSTORE §7| §fhttps://store.xyz.abc" # Action bar message
  discord:
    link: https://discord.gg/xyz
    interval: 140
    sound: "ENTITY_PLAYER_LEVELUP"
    message: |-
      &f
      &9✉ Server Discord

      &fStay up to date with all &9announcements,
      &9gveaways, events &fand much more!

      &9➟ &ndiscord.gg/xyz
      &f
    "action-bar": "§9✉ &lDISCORD §7| §fhttps://discord.gg/xyz"


# DO NOT EDIT
file-version: 1
